export const ADD_FOUND_DEVICE = 'ADD_FOUND_DEVICE';
export const CHANGE_STATE = 'CHANGE_STATE';
export const DELETE_ALL_FOUND_DEVICES = 'DELETE_ALL_FOUND_DEVICES';
export const SET_CONNECTED_DEVICE = 'SET_CONNECTED_DEVICE';
export const SET_MANAGER = 'SET_MANAGER';
